subjects:
  - "国語３"
  - "現代社会"
  - "日本語教育１"
  - "日本語教育２"
  - "微分積分２"
  - "代数・幾何２"
  - "化学"
  - "保健体育３"
  - "Level Up English１"
  - "Level Up English２"
  - "プログラミング２"
  - "情報工学３"
  - "WEBアプリケーション"
  - "電気電子回路"
  - "工業力学１"
  - "材料学"
  - "機械製図"
  - "機械加工実習"
  - "マイコン工学"
  - "計測工学"
  - "工学数理基礎１"
  - "工学数理基礎２"
  - "キャリアデザイン１"
  - "PBL３"
  - "ホームルーム"

schedules:
  A:
    - - ["1, 2限目", "&キャリアデザイン１"]
      - ["3, 4限目", "微分積分２"]
      - ["5~8限目", "機械加工実習"]

    - - ["1, 2限目", "&情報工学３"]
      - ["3, 4限目", "代数・幾何２"]
      - ["5, 6限目", "Level Up English１"]

    - - ["1, 2限目", "国語３"]
      - ["3, 4限目", "現代社会"]
      - ["5, 6限目", "&プログラミング２"]
      - ["7限目", "ホームルーム"]

    - - ["3, 4限目", "&工業力学１"]
      - ["5, 6限目", "保健体育３"]
      - ["7, 8限目", "&工学数理基礎１"]

    - - ["1, 2限目", "化学"]
      - ["3, 4限目", "Level Up English１"]
      - ["5, 6限目", "&PBL３"]

  B:
    - - ["1, 2限目", "&キャリアデザイン１"]
      - ["3, 4限目", "化学"]
      - ["5~8限目", "機械加工実習"]

    - - ["1, 2限目", "&情報工学３"]
      - ["3, 4限目", "Level Up English１"]
      - ["5, 6限目", "保健体育３"]

    - - ["1, 2限目", "現代社会"]
      - ["3, 4限目", "国語３"]
      - ["5, 6限目", "&プログラミング２"]
      - ["7限目", "ホームルーム"]

    - - ["3, 4限目", "&工業力学１"]
      - ["5, 6限目", "代数・幾何２"]
      - ["7, 8限目", "&工学数理基礎１"]

    - - ["1, 2限目", "Level Up English１"]
      - ["3, 4限目", "微分積分２"]
      - ["5, 6限目", "&PBL３"]

timetables:
  "1限目": ["8:50", 45]
  "2限目": ["9:35", 45]
  "3限目": ["10:30", 45]
  "4限目": ["11:15", 45]
  "5限目": ["13:10", 45]
  "6限目": ["13:55", 45]
  "7限目": ["14:50", 45]
  "8限目": ["15:40", 45]
  "9限目": ["16:15", 45]
  "1, 2限目": ["8:50", 90]
  "3, 4限目": ["10:30", 90]
  "5, 6限目": ["13:10", 90]
  "7, 8限目": ["14:50", 90]
  "5~7限目": ["13:10", 150]
  "5~8限目": ["13:10", 190]
  "5~9限目": ["13:10", 230]
  "7~9限目": ["14:45", 135]